apiVersion: install.tetrate.io/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane
  namespace: istio-system
spec:
  hub: $REPO
  telemetryStore:
    elastic:
      host: ${ES_FQDN}
      port: 9200
      selfSigned: true
      version: 7
  managementPlane:
    host: $BRIDGE_ADDRESS_LB
    port: $PORT_LB
    clusterName: $CLUSTER
    organization: $ORG
    selfSigned: true