apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
 name: tsb 
 namespace: tsb 
spec:
 version: 7.13.2
 http:
   service:
     spec:
       type: LoadBalancer
 nodeSets:
   - name: master
     count: 1
     config:
       node.master: true
       node.data: false
       node.ingest: false
   - name: data
     count: 3
     config:
       node.master: false
       node.data: true
       node.ingest: true
     volumeClaimTemplates:
       - metadata:
           name: elasticsearch-data
         spec:
           accessModes:
             - ReadWriteOnce
           resources:
             requests:
               storage: 5Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
 name: tsb
 namespace: tsb
spec:
 version: 7.10.0
 count: 1
 elasticsearchRef:
   name: tsb
 http:
   service:
     spec:
       type: LoadBalancer

