---
apiVersion: install.tetrate.io/v1alpha1
kind: ManagementPlane
metadata:
  namespace: tsb
  name: tsbmgmtplane
spec:
  hub: $REPO_MP
  organization: $ORG
  dataStore:
    postgres:
      host: $(kubectl -n tsb get secrets tsb-pguser-tsb -o go-template='{{.data.host | base64decode}}')
      port: $(kubectl -n tsb get secrets tsb-pguser-tsb -o go-template='{{.data.port | base64decode}}')
      name: $(kubectl -n tsb get secrets tsb-pguser-tsb -o go-template='{{.data.dbname | base64decode}}')
  telemetryStore:
    elastic:
      host: $(kubectl -n tsb get svc tsb-es-http -o go-template='{{.spec.clusterIP}}')
      port: 9200